version: "3.9"

services:
  pwd-checker:
    build: .
    restart: unless-stopped
    environment:
      PORT: "3100"
      GCS_FILE: "/pwned-v8-p50m.gcs"
      DEBUG: "false"
    ports:
      - "3100:3100"
    volumes:
      - type: bind
        source: ./pwned-v8-p50m.gcs
        target: /pwned-v8-p50m.gcs
        read_only: true
